import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { z } from "https://deno.land/x/zod@v3.22.4/mod.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const requestSchema = z.object({
  frontImageUrl: z.string().url(),
  backImageUrl: z.string().url().optional().nullable(),
  instruction: z.string().min(10),
  targetClothingType: z.enum(["t-shirt", "polo", "hoodie", "tops", "sweatshirt"]),
});

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const body = await req.json();
    const parsed = requestSchema.safeParse(body);

    if (!parsed.success) {
      return new Response(JSON.stringify({ error: "Invalid request", details: parsed.error.flatten() }), {
        status: 400,
        headers: corsHeaders,
      });
    }

    const { frontImageUrl, backImageUrl, instruction, targetClothingType } = parsed.data;
    const API_KEY = Deno.env.get("LOVABLE_API_KEY");

    if (!API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    // Unified Prompt
    const prompt = `Generate a PROFESSIONAL apparel mockup for a ${targetClothingType}.
    STRICT COMPOSITION: Show TWO views in ONE single image. LEFT is the FRONT view, RIGHT is the BACK view.
    STYLE: Use a clean, light gray studio background. Match the fabric texture and colors of the reference image exactly.
    USER REQUEST: ${instruction}`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.0-flash", // FIXED MODEL NAME
        messages: [
          {
            role: "user",
            content: [
              { type: "text", text: prompt },
              { type: "image_url", image_url: { url: frontImageUrl } },
              ...(backImageUrl ? [{ type: "image_url", image_url: { url: backImageUrl } }] : []),
            ],
          },
        ],
        modalities: ["image", "text"],
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error("AI Gateway Response Error:", errText);
      throw new Error(`AI Gateway failed: ${response.status}`);
    }

    const data = await response.json();
    console.log("AI Response Data:", JSON.stringify(data));

    // Improved Extraction
    const imageUrl =
      data?.choices?.[0]?.message?.content?.find((c: any) => c.type === "image_url")?.image_url?.url ||
      data?.choices?.[0]?.message?.images?.[0]?.url ||
      null;

    if (!imageUrl) throw new Error("No image generated by AI");

    return new Response(JSON.stringify({ imageUrl }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Function error:", error.message);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: corsHeaders,
    });
  }
});
